### ISSUE TITLE
Feature Request: Map Vote

### ISSUE THREAD

**Issue by CarnageHeart** [ceeeKay/Q2ETweaks#27]
Ability to have a map vote show up before end of map (ex: 2 minutes before timer expires), before score limit is hit (ex: 3/5 points in CTF), before DM score limit is hit (ex: 20/25 frags), or by manual vote start either by console command or through a chat command. Map voting should only be able to be triggered once per map and no sooner than before say 2 minutes into a map. Selection of maps can optionally be customized by votemaplist.txt or automatically populated by detecting maps available in baseq2 or current mod folder if the mod does not have map voting built into it already. Option to replay current map.

**Comment by ceeeKay** [comment]
So there is already map voting built into the game (via ctf codebase, but it's available in FFA too)
`warp_list` controls the list of possible maps that could be warped to (a server admin could generate this)
`warp` is accessible to all players and will print the contents of `warp_list`
`warp <mapname>` will start a vote for a map that's already in the warp list

Unfortunately console players (to my knowledge) don't have bindings for voting yes/no (they'd have to be available in the input/keybindings menu because they can't bind at ~ console). Computer players can bind keys to yes/no or just type yes/no in console.

Admins (via an admin election or the `admin_password` combined with `admin <password>`) can use the warp command without requiring a vote.

Given the important functionality is already present for PC players, and unfortunately not much we can do for consoles without client-side support, I'm not seeing a lot of room for Q2Eaks to add a lot of value/new functionality.

Note I asked about the possibility of options for console players to vote yes/no and ready/unready (for match mode) in the Nightdive Studios discord. Devs replied that it wasn't really intended to be present supported, it's not localized, etc. So not necessarily holding out hope of full console support there.

**Comment by CarnageHeart** [comment]
Ahh geez I keep asking for things that are already in there but hidden huh? lol. Sorry to bother you with my requests not knowing they're already implemented.

**Comment by kevinworth** [comment]
No worries, glad to help spread the knowledge!
