### ISSUE TITLE
Custom Server Message

### ISSUE THREAD

**Issue by deggieq2** [ceeeKay/Q2ETweaks#31]
Hi again

Is it possible to add a custom message when someone joins a server - similar to how it shows whats enabled. The idea would be to show a link to a discord server and other server info!

Thanks!

**Comment by kevinworth** [comment]
Good thinking! Ideally I'd actually like something like this to be configurable really early in the connect process, so that e.g. if you're running a custom map server you can include something like "wait 1-2 minutes for download to complete!" but not sure how early in the process we have the ability to do this.

Minimally we should be able to include a server "message of the day" in the centerprint when a player first gets dropped into the server. Might also be able to implement "motd" in console in case they wanted to re-check it (at least on platforms with console access).

**Comment by ceeeKay** [comment]
Good thinking! Ideally I'd actually like something like this to be configurable really early in the connect process, so that e.g. if you're running a custom map server you can include something like "wait 1-2 minutes for download to complete!" but not sure how early in the process we have the ability to do this.

Minimally we should be able to include a server "message of the day" in the centerprint when a player first gets dropped into the server. Might also be able to implement "motd" in console in case they wanted to re-check it (at least on platforms with console access).

**Comment by ceeeKay** [comment]
Available as of v0.19
